## Add a comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
  "eslint", # typescript-eslint v7 only supports eslint v8
  "ilp-packet" # peg this to same version as sdk-standard-components
]
